# The skupper operator will create a secret from this
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: west-site-cert
  namespace: west
spec:
  ca: skupper-site-ca
  client: true
  subject: skupper-router