# TODO: we are creating this is just so the link-west secret with the proper CA and tls info
# gets generated and we can copy it to the other site (east) with eso, and push secrets
# the downside of this is that this link will never be healthy, and wont be connected to anywhere
# once we can create/use the tls, CA to our site we can drop this
---
apiVersion: skupper.io/v2alpha1
kind: Link
metadata:
  name: link-west-skupper-router
  namespace: west
spec:
  cost: 1
  endpoints:
  - group: skupper-router
    host: skupper-router-inter-router-west.{{ .Values.global.hubClusterDomain }}
    name: inter-router
    port: "443"
  - group: skupper-router
    host: skupper-router-edge-west.{{ .Values.global.hubClusterDomain }}
    name: edge
    port: "443"
  tlsCredentials: link-west
