apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: sample
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 64512
  peerAddress: 10.0.117.112
  # bfdProfile: testbfdprofile
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/worker: ""
  ebgpMultiHop: true
